### ISSUE TITLE
Cannot see project configuration page - js error

### ISSUE THREAD

**Issue by laurentj** [Strider-CD/strider#758] opened 2015-04-12 09:44 UTC
When I go on a project configuration page, tabs are displayed, but tab panels are empty.

During the loading of the page, I have this javascript error

```
TypeError: Cannot read property '1' of null
    at $get (app.js:21379)
    at app.js:20777
    at forEach (app.js:14446)
    at nodeLinkFn (app.js:20764)
    at compositeLinkFn (app.js:20212)
    at compositeLinkFn (app.js:20215)
    at compositeLinkFn (app.js:20215)
    at nodeLinkFn (app.js:20812)
    at compositeLinkFn (app.js:20212)
    at compositeLinkFn (app.js:20215)
```

strider v1.6.6 - Firefox 37 or Chromium 40 (linux)

**Comment by knownasilya** [comment] 2015-04-18 00:08
@laurentj would love a PR. I can't recreate it on OSX, and don't have access to a Linux machine atm.

**Comment by knownasilya** [comment] 2015-06-08 01:04
@laurentj can you help with reproducing this issue?

**Comment by knownasilya** [comment] 2015-06-08 23:18
@laurentj see if master fixes you're issue.

**Comment by knownasilya** [comment] 2015-07-01 20:02
Closing since OP is unresponsive.

**Closed by knownasilya** 2015-07-01 20:02 UTC
Labels: help appreciated, needs confirmation, potential bug, waiting for response
