### ISSUE TITLE
Error connecting to the github account

### ISSUE THREAD

**Issue by alexandrusavin** [Strider-CD/strider#773] opened 2015-05-08 14:25 UTC
If the user hasn't configured his account to publicly display his email account the Github connection fails with an error.

Steps to reproduce:
0. Make your Github emails private in Settings > Emails.
1. Install strider locally
2. create admin user
3. login and try to connect to github account

that you'll get this error:
```
500 TypeError: Cannot read property '0' of undefined
   at makeAccount (/Users/alex/Downloads/strider-1.6.6/node_modules/strider-github/lib/webapp.js:167:28)
   at Strategy.validateAuth [as _verify] (/Users/alex/Downloads/strider-1.6.6/node_modules/strider-github/lib/webapp.js:152:26)
   at /Users/alex/Downloads/strider-1.6.6/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/lib/strategy.js:188:22
   at /Users/alex/Downloads/strider-1.6.6/node_modules/strider-github/node_modules/passport-github/lib/strategy.js:109:5
   at passBackControl (/Users/alex/Downloads/strider-1.6.6/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:126:9)
   at IncomingMessage.<anonymous> (/Users/alex/Downloads/strider-1.6.6/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
   at IncomingMessage.emit (events.js:129:20)
   at _stream_readable.js:908:16
   at process._tickCallback (node.js:355:11)
```

Is it really necessary to have the email public in the Github account in order to connect Strider to it?

**Comment by knownasilya** [comment] 2015-05-08 14:30
Duplicate of #753 and several others :wink:

**Closed by knownasilya** 2015-05-08 14:30 UTC

**Comment by alexandrusavin** [comment] 2015-05-08 15:03
Sorry for the duplicate. I used the HEAD first and than the latest build.
