### ISSUE TITLE
Attempted install 1.7.5, missing dependencies async, strider-cli/.../strider-ecosystem-client

### ISSUE THREAD

**Issue by notbrain** [Strider-CD/strider#886] opened 2015-11-12 00:49 UTC
Just tried to get up to date with the latest release and ran into some strange missing dep errors, when previous install clearly shows they were installed and resident in package.json. Currently running 1.6.6 with no real issues except known bugs via upstart. But when I install and try to manually start 1.7.5, I first got 

    Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/ubuntu/striderNov11/lib/models/upgrade/index.js:3:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.require.upgrade (/home/ubuntu/striderNov11/bin/strider:26:12)
    at module.exports (/home/ubuntu/striderNov11/node_modules/strider-cli/save-user.js:5:22)
    at module.exports (/home/ubuntu/striderNov11/node_modules/strider-cli/add-user.js:9:40)
    at module.exports (/home/ubuntu/striderNov11/node_modules/strider-cli/commands/addUser.js:2:39)
    at /home/ubuntu/striderNov11/node_modules/strider-cli/commands/index.js:14:5

I did an explicit `npm install async` and then again ran `NODE_ENV=production npm start`, and got 

    Error: Cannot find module 'strider-cli/node_modules/strider-ecosystem-client'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/ubuntu/striderNov11/lib/routes/admin/plugins/get_plugin_list.js:8:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/ubuntu/striderNov11/lib/routes/admin/plugins/index.js:4:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/ubuntu/striderNov11/lib/routes/admin/index.js:116:19)

**Comment by notbrain** [comment] 2015-11-12 01:21
I'm on npm 3.3.12 and node 0.12.7. Is this because a bunch of npm 3 changes to downstream dependencies needing explicit install? Any idea how I can fix this without reverting npm?

Also ran `npm ls` after another clean install, and see:

    npm ERR! missing: async@^1.2.1, required by strider@1.7.5
    npm ERR! missing: request@^2.49.0, required by strider@1.7.5
    npm ERR! missing: mkdirp@0.3.x, required by jade@0.35.0
    npm ERR! missing: less@~1.4.2, required by strider-extension-loader@0.4.5
    npm ERR! missing: mkdirp@0.3.x, required by fs-extra@0.8.1
    npm ERR! missing: mkdirp@~0.3.5, required by strider-git@0.1.1
    npm ERR! missing: async@^1.0.0, required by strider-node@0.6.6
    npm ERR! missing: mkdirp@~0.3.5, required by strider-runner-core@2.0.0

**Comment by notbrain** [comment] 2015-11-12 01:37
Ok, after watching strider complain a bunch of times, this series of installs seemed to get things working with npm 3.3.12:

    npm install async@^1.2.1
    npm install request@^2.49.0
    npm install mkdirp@0.3.x
    npm install strider-cli
    npm install lodash
    npm install strider-extension-loader
    npm install bluebird
    npm install step
    npm install cli-table
    npm install debug
    npm install step@0.0.5

And the one dep that needed a dep:

    cd node_modules/strider-cli/
    npm install strider-ecosystem-client

**Comment by knownasilya** [comment] 2015-11-12 13:20
Weird. It might be that someone was using deps of deps at certain levels, and npm 3 does more flattening and they no longer exist? Would love to know where these definitions are.

**Comment by knownasilya** [comment] 2015-11-12 13:54
This looks like a partial duplicate of #885

**Comment by knownasilya** [comment] 2015-11-18 14:05
Also this looks related https://github.com/npm/npm/issues/10277

**Comment by notbrain** [comment] 2015-11-18 16:44
Oooh thanks, marked as a "big-bug", so it should be fixed soon.

**Comment by oliversalzburg** [comment] 2015-11-18 16:45
@notbrain [Don't get your hopes up](https://github.com/npm/npm/issues?q=is%3Aopen+is%3Aissue+label%3Abig-bug) ;D

**Comment by notbrain** [comment] 2015-11-18 16:49
@oliversalzburg only a single page! I'm an optimist ;)

**Comment by notbrain** [comment] 2016-02-22 17:28
This is no longer an issue using npm 3.x and node 5.x; was able to install v1.7.7 with no issues. So more of a backwards compat thing with npm and node.

**Closed** 2016-02-22 17:50 UTC
Labels: help appreciated
