### ISSUE TITLE
Account page not rendered on Firefox 36.0.1 on Ubuntu 14.04

### ISSUE THREAD

**Issue by vishalvinayak** [Strider-CD/strider#747] opened 2015-03-22 15:08 UTC
I can see the menu on the left but when I click on any of the menu items, nothing loads. 
Works perfectly in chrome though.
![selection_001](https://cloud.githubusercontent.com/assets/4641524/6769891/bf61a086-d083-11e4-9db7-6a43e54e62b9.png)

**Comment by knownasilya** [comment] 2015-03-22 16:58
Duplicate of #717

**Closed by knownasilya** 2015-03-22 16:58 UTC
