### ISSUE TITLE
Setup Bitbucket with PLUGIN_BITBUCKET_APP_KEY and _SECRET fails

### ISSUE THREAD

**Issue by natterstefan** [Strider-CD/strider#1036] opened 2017-06-25 08:40 UTC
Hi everybody,

I followed [this guide on strider-cd.github.io](https://strider-cd.github.io/guides/providers/bitbucket.html) and registered a Bitbucket Application. Once I got the Key and Secret I added them to the Strider config:

```
export PLUGIN_BITBUCKET_APP_KEY="appkey"
export PLUGIN_BITBUCKET_APP_SECRET="appsecret"
```

The next step is "Connect Strider With Bitbucket". But as soon as I grant access on bitbucket and redirect back to strider I get an error page saying:

`"Error: Failed to fetch user profile example.com" (Code 500).`

I am not able to add Bitbucket as long as these two variables are exported (see above). When I remove them I can add Bitbucket again. But then I am not sure if the Services work properly as nothing happens when I commit or merge a pull request.

Can someone help me please? Is this [tutorial](https://strider-cd.github.io/guides/providers/bitbucket.html) still relevant?

**Comment by LocoRon** [comment] 2017-06-29 00:46
I was having similar issues.  I fixed them by going into the plugins admin page then removing and re-installing the BitBucket plugin.

**Comment by knownasilya** [comment] 2017-06-29 01:08
Usually happens when you forget server_name initially.

**Comment by natterstefan** [comment] 2017-07-01 15:56
@LocoRon @knownasilya Thank you, gonna test it. Another question: do I need to set `PLUGIN_BITBUCKET_APP_KEY` and `PLUGIN_BITBUCKET_APP_SECRET` to make Bitbucket work?

**Comment by knownasilya** [comment] 2017-07-01 19:14
That is correct.

**Comment by abusquets** [comment] 2017-07-02 22:16
@knownasilya what does you mean with "Usually happens when you forget server_name initially."?
The first time that I started stride I use only

npm start

But now I start the application  in that way

export SERVER_NAME=http://192.168.50.6:3000
export HOST=0.0.0.0
export PORT=3000
export PLUGIN_BITBUCKET_APP_KEY=
export PLUGIN_BITBUCKET_APP_SECRET=
export PLUGIN_GITHUB_APP_ID=
export PLUGIN_GITHUB_APP_SECRET=
export PLUGIN_GITHUB_ACCESS_ORG=

export SMTP_HOST=smtp.gmail.com
export SMTP_PORT=587
export SMTP_USER=""
export SMTP_PASS=""
export SMTP_FROM="@gmail.com"


export DEBUG=strider*
npm start

I also created an OAuth consumer in bitbucket, without url and url callback following other posts recomendations
But I can't use bitbucket, below there is the error message

Connect
500 Error
   at Strategy.OAuthStrategy._createOAuthError (/vagrant/strider/node_modules/strider-bitbucket/node_modules/passport-oauth1/lib/strategy.js:396:17)
   at /vagrant/strider/node_modules/strider-bitbucket/node_modules/passport-oauth1/lib/strategy.js:244:41
   at /vagrant/strider/node_modules/strider-bitbucket/node_modules/oauth/lib/oauth.js:543:17
   at passBackControl (/vagrant/strider/node_modules/strider-bitbucket/node_modules/oauth/lib/oauth.js:397:13)
   at IncomingMessage.<anonymous> (/vagrant/strider/node_modules/strider-bitbucket/node_modules/oauth/lib/oauth.js:409:9)
   at emitNone (events.js:110:20)
   at IncomingMessage.emit (events.js:207:7)
   at endReadableNT (_stream_readable.js:1047:12)
   at _combinedTickCallback (internal/process/next_tick.js:102:11)
   at process._tickDomainCallback (internal/process/next_tick.js:198:9)

**Comment by knownasilya** [comment] 2017-07-03 00:32
Make sure that you clear out Bitbucket auth application, and then run strider with server_name and the bitbucket plugin env vars.

**Comment by abusquets** [comment] 2017-07-03 07:21
@knownasilya you are rigth. I deleted strider and installed again and now I can connect with bitbucket.
Thanks.

**Comment by natterstefan** [comment] 2017-07-03 07:27
@abusquets 

> (...) I deleted strider (...)

Is this really necessary? Isn't it sufficient to

> clear out Bitbucket auth application, and then run strider with server_name and the bitbucket plugin env vars.

**Comment by abusquets** [comment] 2017-07-03 08:27
@natterstefan I don't know. From strider web app, I always got an error

**Comment by xgalen** [comment] 2017-12-05 16:48
So @abusquets, the issue is solved and we can close this, right?

**Comment by natterstefan** [comment] 2017-12-11 18:23
@xgalen from my point of view you can close it. If it is still relevant in the future one can open it again. What do you say @abusquets?

**Closed** 2017-12-18 21:19 UTC
Labels: waiting for response
