### ISSUE TITLE
Duplicate a branch configuration feature

### ISSUE THREAD

**Issue by bariscicek** [Strider-CD/strider#882] opened 2015-11-05 13:58 UTC
Currently it is not possible to duplicate branch configuration in case you want to use same configuration for a new branch. 

You can define a default configuration for master branch, but then it would affect all the non-differentiated branches. This is a nice feature, but in case there is a specialized configuration for a branch, and you want to use it for other branches it is not possible. That is a problem in case branch names are iterative, so for each rc1, rc2, rc3 branches you need to re-do configuration. 

A quick workaround would be possibility to change branch name in branches configuration, which is no non-existing feature, either.

**Comment by knownasilya** [comment] 2015-11-05 14:05
This looks like a duplicate of #876

**Comment by bariscicek** [comment] 2015-11-05 14:08
Indeed I saw that issue before reporting this, however it is a little bit different, because from my understanding '*' is a project Template. Individual branches has also different configurations which should be shared or duplicated if needed.

**Comment by knownasilya** [comment] 2015-11-05 14:10
Even '*' has a branch configuration, that is it uses the 'master' branch's. So really the idea behind project templates and duplicate branch configuration is the same, just different wording. I'm going to close this. Feel free to participate in the other issue.

**Closed by knownasilya** 2015-11-05 14:10 UTC
