### ISSUE TITLE
Error after Oauth connection to Github

### ISSUE THREAD

**Issue by stampfl** [Strider-CD/strider#817] opened 2015-06-23 21:02 UTC
I'm running Strider on a RHEL 6 server behind a corporate firewall. After authorizing strider on my Github profile, the Strider projects page says:
Failed to refresh repositories: [object Object]
![error refreshing](https://cloud.githubusercontent.com/assets/778277/8317103/fd7071e8-19af-11e5-9b26-2cd3475e484c.jpg)
Thanks for your help.

**Comment by knownasilya** [comment] 2015-06-23 21:10
Duplicate of https://github.com/Strider-CD/strider/issues/811, feel free to follow that issue.

**Closed by knownasilya** 2015-06-23 21:10 UTC
