### ISSUE TITLE
Builds stalling and unable to cancel

### ISSUE THREAD

**Issue by jackSnaps** [Strider-CD/strider#1037] opened 2017-07-05 20:00 UTC
Strider occasionally gets stuck 'loading' a build, and the output screen remains black (doesn't show a "prepare" or "test" header). This is particularly annoying because it stalls other builds from occurring. I then cancel the build and manually re-trigger other builds, which work, but for some reason the original, stalled build never actually cancels but just remains in a strange limbo. Any attempt to cancel it just outputs the usual "Got a request to cancel ..." but doesn't actually cancel the job. 

Any ideas on how to prevent the builds from stalling in the first place?

Attached is a screenshot example

![strider_build_stalling](https://user-images.githubusercontent.com/29065963/27882370-6d8a9be6-619a-11e7-967f-a79ea689db21.png)

**Comment by knownasilya** [comment] 2017-07-05 20:04
I think this is a duplicate of https://github.com/Strider-CD/strider/issues/919, We'd love any help you can give in this area 👍

**Closed by knownasilya** 2017-07-05 20:04 UTC

**Comment by jackSnaps** [comment] 2017-07-05 20:06
Slightly similar -- my build doesn't even show the "prepare" stage (the console goes completely black) and refreshing the page causes no issues at all.

**Comment by knownasilya** [comment] 2017-07-05 20:08
I'd start here: https://github.com/Strider-CD/strider-runner-core/blob/master/lib/job.js#L80
