### ISSUE TITLE
Opening /projects crashes strider

### ISSUE THREAD

**Issue by oliversalzburg** [Strider-CD/strider#767] opened 2015-05-02 16:20 UTC
Here's an excerpt for the log:

```
2015-05-02T16:19:23.667Z - info: Fetching projects...

/home/strider/strider/node_modules/strider-gitlab/lib/api.js:28
        callback(err, res.body);
                         ^
TypeError: Cannot read property 'body' of undefined
    at Request._callback (/home/strider/strider/node_modules/strider-gitlab/lib/api.js:28:26)
    at self.callback (/home/strider/strider/node_modules/strider-gitlab/node_modules/request/request.js:129:22)
    at Request.emit (events.js:95:17)
    at ClientRequest.self.clientErrorHandler (/home/strider/strider/node_modules/strider-gitlab/node_modules/request/request.js:239:10)
    at ClientRequest.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1548:9)
    at CleartextStream.emit (events.js:95:17)
    at SecurePair.<anonymous> (tls.js:1400:19)
    at SecurePair.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:980:10)
    at CleartextStream.read [as _read] (tls.js:472:13)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
6504 died 8 null
```

**Comment by oliversalzburg** [comment] 2015-05-02 16:26
Whoops. I guess this belongs into strider-gitlab

**Comment by oliversalzburg** [comment] 2015-05-02 17:25
Was caused by an UNABLE_TO_VERIFY_LEAF_SIGNATURE error due to an incomplete certificate chain on the nginx proxy.

**Comment by knownasilya** [comment] 2015-05-05 14:25
How would I reproduce this issue?

**Comment by oliversalzburg** [comment] 2015-05-05 14:41
Gitlab uses nginx (as a reverse-proxy I assume). I configured that nginx to provide HTTPS and supplied it with our certificate and key. Strider will probably connect to Gitlab over HTTPS by default, if Gitlab is configured this way.

The issue was, I neglected to concatenate our own certificate with the intermediate certificate chain, resulting in an incomplete chain. This causes a certificate chain verification error in NodeJSs networking stack. The result is that the response (`res`) will be undefined.

I'm not too sure about reproducing it, but, I guess, any faulty HTTPS setup on the Git side would cause similar issues.

**Comment by knownasilya** [comment] 2015-05-05 14:43
@oliversalzburg I want to assume that `res` is always there, otherwise this is probably an Express issue.

**Comment by oliversalzburg** [comment] 2015-05-05 14:55
I'm not sure if the response is guaranteed to be there, if there was no response to begin with. Could be worth reporting/discussing at https://github.com/request/request

**Comment by oliversalzburg** [comment] 2015-05-05 21:08
BTW, even if `res` was defined. `res.body` might not be. I have a feeling that this is something that must be handled in strider.

I opened an issue on the request tracker. Let's see what results from it :)

**Comment by knownasilya** [comment] 2015-05-05 21:33
I guess the solution would be to setup a middleware before any routes, and check if `res` is `undefined`.

**Comment by marcuspoehls** [comment] 2015-05-27 08:18
I ran into this issue some time ago. 

**The reason:** wrong GitLab credientials. Providing an unauthorized GitLab token breaks the Strider project overview. 

I shortly described this behaviour in my blog post on how to set up Strider with GitLab: https://futurestud.io/blog/strider-how-to-connect-with-gitlab-and-run-tests-automatically/ 
(”**Attention:** providing wrong credentials will result in disfunction of Strider. The projects overview won’t work anymore.“)

I'll have a deeper look into this issue and try to fix it. PR will be on strider-gitlab plugin, seems to be a problem within the plugin instead of Strider itself.

**Comment by knownasilya** [comment] 2015-05-27 13:55
Yes please. That provider plugin needs a lot of love.

**Comment by marcuspoehls** [comment] 2015-05-30 11:15
The issue was already fixed with **strider-gitlab** plugin version `1.0.5`. Actually, when cloning Strider and install dependencies with `npm install` will use the previous version. You need to reinstall the plugin via admin panel to get the latest version with including fixes.

I created a pull request to bump the strider-gitlab plugin to the latest version while installing Strider from scratch: https://github.com/Strider-CD/strider/pull/782

**Closed** 2015-06-01 13:19 UTC
Labels: potential bug, waiting for response
