### ISSUE TITLE
Status update confusion & duplicate builds UI bug

### ISSUE THREAD

**Issue by jnovack** [Strider-CD/strider#352] opened 2014-02-02 01:45 UTC
When pressing the **Deploy Branch** or **Test Branch** from `http://localhost/repository/config`, it makes two entries in the past builds and the socket does not appear to be accurate as nothing appears to be happening but the deploy (or test) is going.

![screenshot 2014-02-01 20 37 11](https://f.cloud.github.com/assets/387006/2059392/93ba925e-8baa-11e3-88e6-ecea1a4bd2e5.png)

**Comment by oliversalzburg** [comment] 2015-05-05 15:39
@knownasilya If you could point me to where the controller for this part of the UI is located, I might be able to collect some information on this, as I have this happening a lot with our new Strider instance. Our old one doesn't seem to have the issue though...

**Comment by knownasilya** [comment] 2015-05-05 16:01
@oliversalzburg The views are here: 
* `lib/views/partials/_dashboard_row.html` (this is reused for the history and the dashboard -- probably a bad idea..).
* `lib/views/build.html` (above is used on line 66 I think)

All clientside stuff is here: `client/job-status/`

**Comment by oliversalzburg** [comment] 2015-05-05 17:21
So, the problem is not with the `ngRepeat`, that's for sure.

When placing a breakpoint at the start of the `job` controller, you can inspect `global.jobs` and see that there are two jobs marked as "running".

So the error is already in the `jobs` data injected into the page when it is loaded.

**Comment by knownasilya** [comment] 2015-05-05 17:23
@oliversalzburg so it might be some where in one of the files mentioned here #761

**Comment by oliversalzburg** [comment] 2015-05-05 17:29
@knownasilya Maybe. I'm still trying to understand the code a bit better.

I'm assuming that https://github.com/Strider-CD/strider/blob/2e3106a4bb228537727e8953c93efd7d754fcc56/lib/views/build.html is the template which is rendered when I open the build page for a project.

I'm a bit confused how `jobs` is actually rendered and where it's coming from. At first I assumed the moustache syntax indicates that Angular is rendering it, but that doesn't seem right.

So, where is `jobs` actually coming from? I'm assuming it's [`/lib/routes/jobs/index.js`](https://github.com/Strider-CD/strider/blob/b8df992a5721c83b21babd77a4051aaf69890c9a/lib/routes/jobs/index.js). The job sorting approach there seems complicated enough ;D

**Comment by oliversalzburg** [comment] 2015-05-05 18:44
So, I think my assumptions above are correct.

When I log `running` [after the jobs are retrieved](https://github.com/Strider-CD/strider/blob/b8df992a5721c83b21babd77a4051aaf69890c9a/lib/routes/jobs/index.js#L77), I received a single job.

When the jobs are later passed into `res.format`, `jobs` will have 2 entries.

**Comment by oliversalzburg** [comment] 2015-05-05 18:54
Yeah, you're right. I thought a simple `jobs = _.uniq(jobs,"_id");` would fix this, but it doesn't work.

Sadly, I can't get the WebStorm debugger to work with strider, that would make it a bit easier for me ;D

**Comment by oliversalzburg** [comment] 2015-05-05 18:55
But this also explains why I never see this in strider when it's used for a bit of time. I guess 20 jobs is the magic number here ;)

**Comment by oliversalzburg** [comment] 2015-05-05 19:14
Hah, of course, `_id` is an `ObjectId`, so they aren't equal. This works though:

```js
jobs = _.uniq(jobs,function(job){
  return job._id.toString();
});
```

**Closed** 2015-05-05 19:24 UTC
Labels: bug, ui
