### ISSUE TITLE
Currently active run appears twice in Past builds list

### ISSUE THREAD

**Issue by oliversalzburg** [Strider-CD/strider#769] opened 2015-05-02 17:49 UTC
![](http://i.imgur.com/vgjiYoe.png)

Has been happening ever since we started using Strider.

**Comment by knownasilya** [comment] 2015-05-05 14:21
Duplicate of #352

**Closed by knownasilya** 2015-05-05 14:21 UTC

**Comment by knownasilya** [comment] 2015-05-05 14:23
Will be looking into this issue before 1.7.0
