### ISSUE TITLE
addUser -f creates copies of user

### ISSUE THREAD

**Issue by ryanfields** [Strider-CD/strider#754] opened 2015-03-31 18:32 UTC
Subsequent calls to addUser with the -f option for a given user keep inserting new copies of the user.  The -h output suggests that the user entry will be overwritten, so I expect remove/add or update to occur.  Instead, it just runs an insert query on every execution.

**Comment by knownasilya** [comment] 2015-03-31 18:36
Duplicate of #584

**Comment by knownasilya** [comment] 2015-04-18 01:20
Should be fixed with 1.4.7 of strider-cli

**Closed by knownasilya** 2015-04-18 01:20 UTC
Labels: needs confirmation
