### ISSUE TITLE
Post-install fails

### ISSUE THREAD

**Issue by timbeadle** [Strider-CD/strider#699] opened 2015-01-22 21:54 UTC
I've tried to install on two separate OS X Yosemite machines & both give the same error:

```
> bower install --config.interactive=false --allow-root && npm run build


Error: EACCES, permission denied '/Users/timbeadle/.config/configstore/insight-bower.yml'
You don't have access to this file.

    at Object.fs.openSync (evalmachine.<anonymous>:438:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:289:15)
    at Object.create.all.get (/usr/local/lib/node_modules/strider/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/local/lib/node_modules/strider/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/local/lib/node_modules/strider/node_modules/bower/node_modules/insight/lib/index.js:26:34)
    at ensureInsight (/usr/local/lib/node_modules/strider/node_modules/bower/lib/util/analytics.js:26:19)
    at Object.setup (/usr/local/lib/node_modules/strider/node_modules/bower/lib/util/analytics.js:43:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/strider/node_modules/bower/bin/bower:72:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "strider"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.7
npm ERR! code ELIFECYCLE

npm ERR! strider@1.6.2 postinstall: `bower install --config.interactive=false --allow-root && npm run build`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the strider@1.6.2 postinstall script.
npm ERR! This is most likely a problem with the strider package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install --config.interactive=false --allow-root && npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls strider
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/timbeadle/npm-debug.log
```

This is installing using `sudo npm install -g strider`

**Comment by timbeadle** [comment] 2015-01-22 21:57
npm-debug.log: https://gist.github.com/timbeadle/9f57192d743e0a83c321

**Comment by knownasilya** [comment] 2015-01-23 13:51
Permissions issues. Duplicate of #687

**Closed by knownasilya** 2015-01-23 13:51 UTC
