### ISSUE TITLE
Deploy to Heroku button fails

### ISSUE THREAD

**Issue by csu** [Strider-CD/strider#778] opened 2015-05-26 18:37 UTC
Breaks on the "Build app" phase.
Full build log: https://gist.github.com/csu/6cbc830ade3bb403f5bb
Seems to be a Heroku problem though (???)

**Comment by knownasilya** [comment] 2015-05-26 18:38
Duplicate of #716

**Comment by knownasilya** [comment] 2015-05-26 18:38
Feel free to continue discussion in that issue.

**Comment by csu** [comment] 2015-05-26 18:39
@knownasilya Ah, thanks. Thought it was a different error because it looked like `npm install` was successful.

**Closed by knownasilya** 2015-05-26 18:38 UTC

**Comment by knownasilya** [comment] 2015-05-26 18:40
Sorry, I think it was actually #433
