### ISSUE TITLE
Installating Error

### ISSUE THREAD

**Issue by thakerng** [Strider-CD/strider#697] opened 2015-01-21 19:30 UTC
When I run `npm install strider -g` under root on Ubuntu 14.04 64 bit 
- node v 0.10.35 
- npm v 1.4.28

I got the permission error

```
> strider@1.6.2 postinstall /usr/lib/node_modules/strider
> bower install --config.interactive=false --allow-root && npm run build


Error: EACCES, permission denied '/root/.config/configstore/insight-bower.yml'
You don't have access to this file.

    at Object.fs.openSync (evalmachine.<anonymous>:439:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:290:15)
    at Object.create.all.get (/usr/lib/node_modules/strider/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/lib/node_modules/strider/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/lib/node_modules/strider/node_modules/bower/node_modules/insight/lib/index.js:26:34)
    at ensureInsight (/usr/lib/node_modules/strider/node_modules/bower/lib/util/analytics.js:26:19)
    at Object.setup (/usr/lib/node_modules/strider/node_modules/bower/lib/util/analytics.js:43:9)
    at Object.<anonymous> (/usr/lib/node_modules/strider/node_modules/bower/bin/bower:72:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

npm ERR! strider@1.6.2 postinstall: `bower install --config.interactive=false --allow-root && npm run build`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the strider@1.6.2 postinstall script.
npm ERR! This is most likely a problem with the strider package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install --config.interactive=false --allow-root && npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls strider
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-43-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "strider" "-g"
npm ERR! cwd /root
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by knownasilya** [comment] 2015-01-21 19:40
There's a note in the README about this:

>Note: Sometimes there are issues with permissions and installing global modules, in those cases run npm config set prefix ~/npm to set your global modules directory to '~/npm'.

**Comment by knownasilya** [comment] 2015-01-21 19:41
Duplicate of #687

**Closed by knownasilya** 2015-01-21 19:41 UTC

**Comment by djensen47** [comment] 2015-06-08 05:54
I think you're punting on an actual issue. I'm seeing this with `sudo npm install -g strider`

If I'm sudo, I shouldn't have permissions issues.

**Comment by djensen47** [comment] 2015-06-08 05:57
No matter how I try this I get a similar error. It seems to complain about directories that don't exist.

**Comment by oliversalzburg** [comment] 2015-06-08 08:36
@djensen47 What are the errors you are receiving?

**Comment by knownasilya** [comment] 2015-06-08 12:04
@djensen47 try master. Bower has been removed , just remember to run `npm run build`

**Comment by knownasilya** [comment] 2015-06-08 12:09
`npm install -g Strider-CD/strider`
